export const REGISTER_USER = "REGISTER_USER"
export const REGISTER_USER_SUCCESSFUL = "REGISTER_USER_SUCCESSFUL"
export const REGISTER_ERROR = "REGISTER_ERROR"
export const RESET_REGISTER_FLAG = "RESET_REGISTER_FLAG";
