import React, { useEffect, useState } from "react";
import styles from "./privacy.module.scss";

function PrivacyPolicyBody() {
  return (
    <div>

    <div className={styles.commonBsec}>
      <div className={styles.containerfluid}> 
        <div className={styles.PrivacyPolicyBodySec}>
          <h2>Privacy Policy</h2>
          <p>Last updated: January 13, 2023</p>
          <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
          <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Free Privacy Policy Generator.</p>
          <h3>Interpretation and Definitions</h3>
          <h4>Interpretation</h4>
          <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
          <h4>Definitions</h4>
          <p>For the purposes of this Privacy Policy:</p>
          <ul>
            <li>Account means a unique account created for You to access our Service or parts of our Service.</li>
            <li>Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to courtiers, 1425 rue St-Denis, Montreal, Quebec H7P 2J4.</li>
            <li>Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
            <li>Country refers to: Alberta, Canada</li>
            <li>Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
            <li>Personal Data is any information that relates to an identified or identifiable individual.</li>
            <li>Service refers to the Website.</li>
            <li>Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Compan.</li>
            <li>Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
            <li>Website refers to courtiers, accessible from www.courtiers.com</li>
            <li>You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
          </ul>
          <h3>Collecting and Using Your Personal Data</h3>
          <h4>Types of Data Collected</h4>
          <h4>Personal Data</h4>
          <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
          <ul>
            <li>First name and last name</li>
            <li>Usage Data</li>
          </ul>
          <h4>Usage Data</h4>
          <p>Usage Data is collected automatically when using the Service.<br/>
          Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those</p>
        </div>
      </div>
    </div>

    
    </div>
    
     
  );
}

export default PrivacyPolicyBody;